### DISCUSSION TITLE
How to make bubble cards use the same color as tile cards

### DISCUSSION THREAD

**Discussion by D3SOX** [Nerwyn/material-you-theme#84] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/0a064a92-6d62-4479-b56e-1d8272454828)

Why is it using a different color here?

**Comment by Nerwyn** [comment]
Bubble cards do not use the same colors as tile/default cards. This is what they look like in the default theme.
![image](https://github.com/user-attachments/assets/f47500cf-58c9-4e33-b005-45a41a434bba)

**Reply by D3SOX** [reply]
Is there any way to make them look the same? I already fiddled around with the click/hold actions to make them consistent with tile cards and saw that there already are styling variables set in the theme for Bubble card but it still looks different, especially the background colors

**Reply by Nerwyn** [reply, marked as answer]
In the bubble card popup custom styles, to make tiles/default cards look like bubble cards:

```css
:host {
  --ha-card-background: var(--bubble-main-background-color);
  --ha-card-box-shadow: var(--bubble-box-shadow);
  --ha-card-border-radius: var(--bubble-border-radius);
  --ha-card-border-width: 2px;
  --ha-card-border-color: transparent;
}
```

And to make bubble cards look like tiles/default cards:

```css
:host {
  --bubble-main-background-color: var(--ha-card-background);
  --bubble-box-shadow: var(--ha-card-box-shadow);
  --bubble-border-radius: var(--ha-card-border-radius);
}
.card-content > div {
  border: var(--ha-card-border-width) solid var(--ha-card-border-color);
}
```
