### DISCUSSION TITLE
Transparency in cards

### DISCUSSION THREAD

**Discussion by omarleomar** [Nerwyn/material-you-theme#9] [Q&A] [answered]
Hello,

First of all, thank you for your work, it's really great !

I have a question, in my dashboard I put a background image and I would like my cards to be transparent so I can see my background like in the iOS theme for example...

Could you help me ?

Thanks a lot :)

**Comment by Nerwyn** [comment, marked as answer]
I added a `Material Rounded Transparent Card` version of the theme in v1.5.2 a couple of weeks ago that may work for you if you set the theme at the card level. Otherwise you should use card-mod:

```yaml
card_mod:
  style: |
    ha-card {
      background: none;
    }
```
