### ISSUE TITLE
Bubble Card Pop-Up Margin not respected

### ISSUE THREAD

**Issue by TheBToby** [Nerwyn/material-you-theme#80]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:**
4.0.2

**Last working release (if known):**

**Browser and Operating System:**
- Client: iOS 18.4.1
- Home Assistant: Core: 2025.4.3
- Home Assistant: Supervisor: 2025.04.0
- Home Assistant: Operating System: 15.2
- Home Assistant: Frontend: 20250411.0

**Description of problem:**
When defining the "margin_top_mobile" attribute of a bubble pop-up card, the attribute gets applied to the pop-up itself but not the title. In my case, the title now overlaps the content of the pop-up card (see screenshot).
This only happens when applying the "Material You Theme", not for any other themes.

![Image](https://github.com/user-attachments/assets/6841769f-7df0-41df-85e0-ffef02c57b75)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
Can you share your card config? I'm having trouble reproducing this.

**Comment by TheBToby** [comment]
Sure! FYI I'm using the lovelace_gen plugin to import multiple cards to the pop-up card. However, the configuration below only shows the first import (to keep it short). The same y-offset on the title appears on every pop-up card, independent of the content, though.

```yaml
      # Pop-up Rooms
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#pop-up-rooms'
            name: Räume
            icon: mdi:home-search
            card_layout: large
            margin_top_mobile: '-56px'
            close_by_clicking_outside: true
          # Room: Erdgeschoss
          - !include
            - room_card.yaml
            - name: "Erdgeschoss"
              clima: climate.klima_sensor_thermostat_wohnzimmer
              valve: sensor.homematic_sv_ventil_eg_wohnzimmer
              clima2: climate.klima_sensor_thermostat_kuche
              valve2: sensor.homematic_sv_ventil_eg_kuche
              light: light.erdgeschoss
              light_group:
                - light.eg_eingang
                - light.eg_esstisch_oben
                - light.eg_esstisch_unten
                - light.eg_kuche
                - light.eg_lounge
                - light.eg_kuche_hangeschrank_oben_links
                - light.eg_kuche_hangeschrank_oben_rechts
                - light.eg_kuche_hangeschrank_unten
                - light.eg_kuche_oberschrank_unten
                - light.eg_woodupp
              light_scenes:
                - scene.erdgeschoss_tv
                - scene.erdgeschoss_essen
              light2: light.nanoleaf
              light2_group:
                - light.nanoleaf
              light2_scenes:
              speaker: media_player.lounge
              speaker2: media_player.move
              tv: media_player.samsung_tv
              icon: mdi:sofa
              icon_color: black
              icon_background: "#FFC47Eaa"

```
