### ISSUE TITLE
2025.5 - Dashboard layout inconsistancy with Bubble Cards

### ISSUE THREAD

**Issue by JordyEGNL** [Nerwyn/material-you-theme#89]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:** 2025.5.1 with 4.0.6

**Last working release (if known):** 2025.4 with 4.0.?

**Browser and Operating System:** Android and Web

**Description of problem:** When there is a Bubble Card with a normal Tile card there is no spacing between the two.

In the screenshot below the bottom 2 cards are 'Tile' and the others are Bubble Card

![Image](https://github.com/user-attachments/assets/2a12ae1c-feb8-4ca3-90b0-063314843946)

**Comment by Nerwyn** [comment]
That's a weird one. I can't seem to recreate it. Can you share your config?

![Image](https://github.com/user-attachments/assets/d969f5e8-4729-405f-a6ba-933acf6be130)

**Comment by JordyEGNL** [comment]
Yeah of course!

```yaml
title: Slaapkamer
path: slaapkamer-jordy
icon: mdi:bed
theme: Material You
type: sections
max_columns: 1
sections:
  - type: grid
    cards:
      - type: heading
        heading: Slaapkamer Jordy
        heading_style: title
        icon: mdi:bed
        badges:
          - type: entity
            show_state: true
            show_icon: true
            entity: sensor.slaapkamer_temperature_temperature
            color: primary
            tap_action:
              action: more-info
          - type: entity
            show_state: true
            show_icon: true
            entity: sensor.slaapkamer_temperature_humidity
            color: primary
            tap_action:
              action: more-info
      - type: heading
        icon: ""
        heading_style: subtitle
        heading: Apparaten
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.bureau_ledstrip
        show_state: true
        slider_live_update: false
        show_attribute: true
        attribute: brightness
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        card_layout: large
        grid_options:
          columns: 6
          rows: 1
        styles: |-
          .bubble-button-card-container{
            background: var(--md-sys-color-surface-container-low);
          }
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.bed_ledstrip
        show_state: true
        slider_live_update: false
        show_attribute: true
        attribute: brightness
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        card_layout: large
        grid_options:
          columns: 6
          rows: 1
        styles: |-
          .bubble-button-card-container{
            background: var(--md-sys-color-surface-container-low);
          }
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.slaapkamer_plafondlamp
        show_state: true
        slider_live_update: false
        show_attribute: true
        attribute: brightness
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        card_layout: large
        name: Plafondlamp
        use_accent_color: false
        force_icon: false
        show_last_changed: false
        styles: |-
          .bubble-button-card-container{
            background: var(--md-sys-color-surface-container-low);
          }
      - type: tile
        entity: switch.computer_jordy
        show_entity_picture: false
        vertical: false
        hide_state: false
        icon: ""
        color: primary
        icon_tap_action:
          action: perform-action
          perform_action: script.computer_jordy_aanzetten
          target: {}
        grid_options:
          columns: 6
          rows: 1
      - type: tile
        entity: switch.beeldschermen
        layout_options:
          grid_columns: 2
```
